### ISSUE TITLE
Introduce some level of Gitflow

### ISSUE THREAD

**Issue by atticoos** [SandersForPresident/BernieAppAndroid#4]
Right now `master` is "all the things".

First step towards a more stabilized environment would be to immediately create a `develop` branch and assign it as the default branch for the project. All things should be branched off of this. `master` should only receive merges at milestone completions, or bugfixes, both in which are stable

**Comment by svengeance** [comment]
I've taken it into consideration.

And done/am doing it. Thanks ;)
